const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Multiplayer,
		C3.Plugins.LocalStorage,
		C3.Plugins.Share,
		C3.Plugins.advert,
		C3.Plugins.Touch,
		C3.Plugins.Arr,
		C3.Plugins.PlatformInfo,
		C3.Plugins.CORDOVAIAP,
		C3.Plugins.Audio,
		C3.Plugins.AJAX,
		C3.Plugins.InstantGames,
		C3.Plugins.Mouse,
		C3.Plugins.Dictionary,
		C3.Plugins.video,
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Behaviors.Pin,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Flash,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Plugins.Button,
		C3.Plugins.TextBox,
		C3.Plugins.List,
		C3.Behaviors.MoveTo,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.List.Acts.SetCSSStyle,
		C3.Plugins.List.Cnds.CompareInstanceVar,
		C3.Plugins.List.Acts.Select,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.List.Cnds.CompareSelectedText,
		C3.Plugins.TextBox.Cnds.CompareInstanceVar,
		C3.Plugins.TextBox.Acts.SetEnabled,
		C3.Plugins.TextBox.Acts.SetPlaceholder,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Browser.Acts.Alert,
		C3.Plugins.List.Cnds.OnSelectionChanged,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Browser.Cnds.OnBackButton,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.CORDOVAIAP.Cnds.ProductOwned,
		C3.Plugins.PlatformInfo.Cnds.IsWebExport,
		C3.Plugins.advert.Acts.HideBanner,
		C3.Plugins.PlatformInfo.Cnds.IsCordovaExport,
		C3.Plugins.advert.Cnds.IsBannerLoaded,
		C3.Plugins.advert.Acts.CreateBanner,
		C3.Plugins.advert.Cnds.IsInterstitialLoaded,
		C3.Plugins.advert.Acts.CreateInterstitial,
		C3.Plugins.advert.Cnds.IsVideoLoaded,
		C3.Plugins.advert.Acts.CreateVideo,
		C3.Plugins.advert.Cnds.IsShowingBanner,
		C3.Plugins.advert.Acts.ShowBanner,
		C3.Plugins.advert.Cnds.IsShowingVideo,
		C3.Plugins.advert.Acts.ShowVideo,
		C3.Plugins.advert.Cnds.IsShowingInterstitial,
		C3.Plugins.advert.Acts.ShowInterstitial,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.PlatformInfo.Exps.ScreenHeight,
		C3.Plugins.PlatformInfo.Exps.ScreenWidth,
		C3.Plugins.CORDOVAIAP.Acts.RegisterProduct,
		C3.Plugins.CORDOVAIAP.Acts.CompleteRegistration,
		C3.Plugins.PlatformInfo.Cnds.IsOnChromeOS,
		C3.Plugins.InstantGames.Cnds.IsAvailable,
		C3.Plugins.InstantGames.Acts.SubscribeBot,
		C3.Plugins.InstantGames.Acts.CreateShortcut,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.System.Acts.SetCanvasSize,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportleft
	];
};
self.C3_JsPropNameTable = [
	{Browser: 0},
	{Keyboard: 0},
	{Multiplayer: 0},
	{LocalStorage: 0},
	{Share: 0},
	{MobileAdvert: 0},
	{Touch: 0},
	{ArrayX: 0},
	{ArrayAI: 0},
	{ArrayGame: 0},
	{ArrayO: 0},
	{ArrayPlayer: 0},
	{PlatformInfo: 0},
	{MobileIAP: 0},
	{Audio: 0},
	{AJAX: 0},
	{InstantGames: 0},
	{Mouse: 0},
	{Dictionary: 0},
	{Video: 0},
	{id: 0},
	{Ludo_arrow: 0},
	{Ludo_back: 0},
	{Ludo_bgPattern: 0},
	{Tween: 0},
	{Ludo_bgPattern2: 0},
	{Pin: 0},
	{Ludo_btnCancel: 0},
	{Ludo_btnOk: 0},
	{Ludo_BtnPlay: 0},
	{Ludo_btnPlyr: 0},
	{Type: 0},
	{Ludo_Button: 0},
	{ID: 0},
	{Ludo_dice: 0},
	{isRolling: 0},
	{Ludo_diceAnim: 0},
	{Player: 0},
	{Ludo_diceBg: 0},
	{ludo: 0},
	{DragDrop: 0},
	{popBG: 0},
	{color: 0},
	{preview: 0},
	{stop: 0},
	{player: 0},
	{pos: 0},
	{status: 0},
	{canMove: 0},
	{isMoving: 0},
	{canKill: 0},
	{tBlue: 0},
	{tGreen: 0},
	{Flash: 0},
	{tokenBG: 0},
	{yellow: 0},
	{green: 0},
	{red: 0},
	{blue: 0},
	{isStop: 0},
	{Sine: 0},
	{track: 0},
	{tRed: 0},
	{tYellow: 0},
	{win: 0},
	{winPlace: 0},
	{color_selected: 0},
	{Ludo_color: 0},
	{Ludo_btnPlaytxt: 0},
	{Ludo_ButtonReset: 0},
	{Fade: 0},
	{MSG: 0},
	{playerBG: 0},
	{playerNames: 0},
	{playerText: 0},
	{reset: 0},
	{LudoTiledBackground: 0},
	{LudoPathHighlighter: 0},
	{LudoBoard2: 0},
	{LudoSelectionBG: 0},
	{InAction: 0},
	{Button1: 0},
	{Button2: 0},
	{Enable: 0},
	{TextInput1: 0},
	{TextInput2: 0},
	{Button3: 0},
	{ProfileBelongsTo: 0},
	{Text1: 0},
	{Text2: 0},
	{TextInput3: 0},
	{TextInput4: 0},
	{Text3: 0},
	{ButtonNav: 0},
	{SendButton: 0},
	{Winner: 0},
	{IIDValue: 0},
	{TextApp: 0},
	{Text4: 0},
	{txtNote: 0},
	{txtAI: 0},
	{Divider: 0},
	{TextCreators: 0},
	{Ludo_TextInput: 0},
	{TiledBackground2: 0},
	{ButtonBack: 0},
	{ButtonAudio: 0},
	{ScoreBoard: 0},
	{Ludo_List: 0},
	{Sprite: 0},
	{Ochuchoa_Text: 0},
	{TextsOther: 0},
	{TextInputs: 0},
	{Btn: 0},
	{LudoBoard: 0},
	{MoveTo: 0},
	{LudoToken: 0},
	{BtnAudio: 0},
	{BtnAlignLeft: 0},
	{itemID: 0},
	{PlayerNumber: 0},
	{diceCount: 0},
	{Ludo_diceTurn: 0},
	{Ludo_playersCount: 0},
	{Ludo_playersWinCount: 0},
	{Ludo_gameOver: 0},
	{Ludo_P1: 0},
	{Ludo_P2: 0},
	{Ludo_P3: 0},
	{Ludo_P4: 0},
	{Ludo_AI1: 0},
	{Ludo_AI2: 0},
	{Ludo_AI3: 0},
	{Ludo_AI4: 0},
	{Ludo_Player1Wins: 0},
	{Ludo_Player2Wins: 0},
	{Ludo_Player3Wins: 0},
	{Ludo_Player4Wins: 0},
	{Ludo_Player: 0},
	{Ludo_targetPOS: 0},
	{currentPlayer: 0},
	{diceRolled: 0},
	{playerMove: 0},
	{reachPosition: 0},
	{diceRolledSix: 0},
	{LudoTokenMoveCount: 0},
	{movePosition: 0},
	{AIPickCanKill: 0},
	{AIPickCanWin: 0},
	{AIPickCanMove: 0},
	{TokensCount: 0},
	{TokenWins: 0},
	{TokenWinCount: 0},
	{TokenMoveCountLocal: 0},
	{Ludo_trackPosition: 0},
	{PlayerID: 0},
	{TokenID: 0},
	{GameOver: 0},
	{NoAd: 0},
	{InstantAppAdsInterstitial: 0},
	{web_app_url: 0},
	{fb_share_url: 0},
	{android_share_url: 0},
	{ios_share_url: 0},
	{WhosTurn: 0},
	{Temp1: 0},
	{Temp2: 0},
	{WhosTurn3: 0},
	{JustOpened: 0},
	{PlayerMode: 0},
	{Game: 0},
	{TotalGames: 0},
	{InviteCode: 0},
	{Username: 0},
	{PlayFabID: 0},
	{SelectedGame: 0},
	{Page: 0},
	{JoinedAsHostPeer: 0},
	{WinsTotal: 0},
	{WinsMine: 0},
	{Tie: 0},
	{WinsOpponent: 0},
	{AspectRatio: 0},
	{FriendUsername: 0},
	{CellState: 0},
	{GameState: 0},
	{GAME_NAME: 0},
	{INSTANCE_NAME: 0},
	{ROOM_NAME: 0},
	{AndroidBannerAd: 0},
	{AndroidAdInter: 0},
	{AndroidAdReward: 0},
	{AndroidAdOverlay: 0},
	{AndroidAdNative: 0},
	{ChooseAd: 0}
];

self.InstanceType = {
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Multiplayer: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Share: class extends self.IInstance {},
	MobileAdvert: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	ArrayX: class extends self.IArrayInstance {},
	ArrayAI: class extends self.IArrayInstance {},
	ArrayGame: class extends self.IArrayInstance {},
	ArrayO: class extends self.IArrayInstance {},
	ArrayPlayer: class extends self.IArrayInstance {},
	PlatformInfo: class extends self.IInstance {},
	MobileIAP: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	InstantGames: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Dictionary: class extends self.IDictionaryInstance {},
	Video: class extends self.IWorldInstance {},
	Ludo_arrow: class extends self.ISpriteInstance {},
	Ludo_back: class extends self.ISpriteInstance {},
	Ludo_bgPattern: class extends self.ITiledBackgroundInstance {},
	Ludo_bgPattern2: class extends self.ITiledBackgroundInstance {},
	Ludo_btnCancel: class extends self.ISpriteInstance {},
	Ludo_btnOk: class extends self.ISpriteInstance {},
	Ludo_BtnPlay: class extends self.ISpriteInstance {},
	Ludo_btnPlyr: class extends self.ISpriteInstance {},
	Ludo_Button: class extends self.ISpriteInstance {},
	Ludo_dice: class extends self.ISpriteInstance {},
	Ludo_diceAnim: class extends self.ISpriteInstance {},
	Ludo_diceBg: class extends self.ISpriteInstance {},
	ludo: class extends self.ISpriteInstance {},
	popBG: class extends self.ISpriteInstance {},
	preview: class extends self.ISpriteInstance {},
	stop: class extends self.ISpriteInstance {},
	tBlue: class extends self.ISpriteInstance {},
	tGreen: class extends self.ISpriteInstance {},
	tokenBG: class extends self.ISpriteInstance {},
	track: class extends self.ISpriteInstance {},
	tRed: class extends self.ISpriteInstance {},
	tYellow: class extends self.ISpriteInstance {},
	win: class extends self.ISpriteInstance {},
	winPlace: class extends self.ISpriteInstance {},
	Ludo_color: class extends self.ISpriteInstance {},
	Ludo_btnPlaytxt: class extends self.ITextInstance {},
	Ludo_ButtonReset: class extends self.ISpriteInstance {},
	MSG: class extends self.ITextInstance {},
	playerBG: class extends self.ISpriteInstance {},
	playerNames: class extends self.ITextInstance {},
	playerText: class extends self.ITextInstance {},
	reset: class extends self.ITextInstance {},
	LudoTiledBackground: class extends self.ITiledBackgroundInstance {},
	LudoPathHighlighter: class extends self.ISpriteInstance {},
	LudoBoard2: class extends self.ISpriteInstance {},
	LudoSelectionBG: class extends self.ISpriteInstance {},
	Button1: class extends self.IButtonInstance {},
	Button2: class extends self.IButtonInstance {},
	TextInput1: class extends self.ITextInputInstance {},
	TextInput2: class extends self.ITextInputInstance {},
	Button3: class extends self.IButtonInstance {},
	Text1: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	TextInput3: class extends self.ITextInputInstance {},
	TextInput4: class extends self.ITextInputInstance {},
	Text3: class extends self.ITextInstance {},
	ButtonNav: class extends self.ISpriteInstance {},
	SendButton: class extends self.IButtonInstance {},
	TextApp: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	txtNote: class extends self.ITextInstance {},
	txtAI: class extends self.ITextInstance {},
	Divider: class extends self.ISpriteInstance {},
	TextCreators: class extends self.ITextInstance {},
	Ludo_TextInput: class extends self.ITextInputInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	ButtonBack: class extends self.ISpriteInstance {},
	ButtonAudio: class extends self.ISpriteInstance {},
	ScoreBoard: class extends self.ISpriteInstance {},
	Ludo_List: class extends self.IListInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Ochuchoa_Text: class extends self.ISpriteInstance {},
	TextsOther: class extends self.ITextInstance {},
	TextInputs: class extends self.ITextInputInstance {},
	Btn: class extends self.ISpriteInstance {},
	LudoBoard: class extends self.ISpriteInstance {},
	LudoToken: class extends self.ISpriteInstance {},
	BtnAudio: class extends self.ISpriteInstance {},
	BtnAlignLeft: class extends self.ISpriteInstance {}
}